### ISSUE TITLE
Local device clock drift + offset induced by mDash

### ISSUE THREAD

**Issue by ssbrewco** [cesanta/mDash#14]
Release 1.2.14 introduced an "hourly automatic NTP sync". Unfortunately this change also introduced a time offset in the local device clock. In our testing this offset is about 30-32 minutes vs. UTC. This was seen across our entire fleet. Manual NTP syncs were quickly overridden by the mDash automatic & erroneous syncs.

Reverting to 1.2.13 resolves the issue. Strongly recommend rolling back the changes introduced in 1.2.14

**Comment by cpq** [comment]
That should be fixed now - closing.
