### ISSUE TITLE
can not compile mdash library

### ISSUE THREAD

**Issue by ashishmac7** [cesanta/mDash#2]
when i am trying to compile example code of mdash, arduino ide throws error as shown below.

c:/users/ashish/downloads/arduino-1.8.9-windows/arduino-1.8.9/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\ashish\AppData\Local\Temp\arduino_build_145131/Shadow.ino.elf section `.text1' will not fit in region `iram1_0_seg'

c:/users/ashish/downloads/arduino-1.8.9-windows/arduino-1.8.9/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\ashish\Documents\Arduino\libraries\mDash\src\esp8266\libmDash.a: in function `mDashCLI':

/Users/lsm/src/cesanta.com/alib/cli.c:66: undefined reference to `recvfrom'

c:/users/ashish/downloads/arduino-1.8.9-windows/arduino-1.8.9/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: /Users/lsm/src/cesanta.com/alib/cli.c:66: undefined reference to `sendto'

c:/users/ashish/downloads/arduino-1.8.9-windows/arduino-1.8.9/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\ashish\Documents\Arduino\libraries\mDash\src\esp8266\libmDash.a: in function `serve_dns':

/Users/lsm/src/cesanta.com/alib/cli.c:75: undefined reference to `recvfrom'

c:/users/ashish/downloads/arduino-1.8.9-windows/arduino-1.8.9/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\ashish\Documents\Arduino\libraries\mDash\src\esp8266\libmDash.a: in function `serve_dns':

/Users/lsm/src/cesanta.com/alib/dns.c:41: undefined reference to `sendto'

collect2.exe: error: ld returned 1 exit status

Using library mDash at version 1.0.45 in folder: C:\Users\ashish\Documents\Arduino\libraries\mDash 
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

**Comment by cpq** [comment]
Try to define a dummy `sendto()` function in your firmware.
Also, please update to the latest mdash version.

NOTE - ESP8266 support is limited, there is no OTA and no TLS so far.

Closing for now, please reopen if still fails.
