### ISSUE TITLE
100% Progress bar stuck

### ISSUE THREAD

**Issue by PoojaG20** [cesanta/mDash#3]
![image](https://user-images.githubusercontent.com/20612889/65622538-7ed57780-dfe3-11e9-80d5-ba433c90c4ea.png)

in mDash I see 100% progress bar for the firmware update of ESP32, which does not let the shadow states update ..

**Comment by PoojaG20** [comment]
It does not get to completion state when updated via OTA from some days. How to resolve it?

**Comment by cpq** [comment]
My guess it is the timer task OOMing.
Do you see the logs in the serial console?
