### ISSUE TITLE
ESP8266 Fails to compile under the Arduino IDE

### ISSUE THREAD

**Issue by sfranzyshen** [cesanta/mDash#4]
LINUX_DIST="Linux Mint 18.3 Sylvia MATE 32-bit"
KERNEL=Linux computer 4.10.0-38-generic i686 i686 i686 GNU/Linux

ARDUINO IDE: 1.8.10 (32bit)
mDash Library: 1.1.8 (Installed using Arduino IDE library manager)
ESP8266 BOARD: 2.5.2 (Installed with board manager from Arduino IDE)

OUTPUT:
```

/home/name/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: /home/name/Arduino/libraries/mDash/src/esp8266/libmDash.a:(.irom0.text.mDash.c.212.89+0x54): undefined reference to `esp_random'
/home/name/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: /home/name/Arduino/libraries/mDash/src/esp8266/libmDash.a:(.irom0.text.mDash.c.212.89+0xa4): undefined reference to `esp_random'
collect2: error: ld returned 1 exit status
exit status 1
```

**Comment by sfranzyshen** [comment]
LINUX_DIST="Linux Mint 18.3 Sylvia MATE 32-bit"
KERNEL=Linux computer 4.10.0-38-generic i686 i686 i686 GNU/Linux

ARDUINO IDE: 1.8.10 (32bit)
mDash Library: 1.1.8 (Installed using Arduino IDE library manager)
ESP8266 BOARD: 2.6.0-dev (Installed manually into the Arduino IDE)

OUTPUT:
```
/home/name/Arduino/hardware/esp8266com/esp8266/tools/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: /tmp/arduino_build_253567/Minimal.ino.elf section `.text1' will not fit in region `iram1_0_seg'
collect2: error: ld returned 1 exit status
Using library mDash at version 1.1.8 in folder: /home/name/Arduino/libraries/mDash 
Using library WiFi at version 1.2.7 in folder: /home/name/arduino-1.8.10/libraries/WiFi 
Using library SPI at version 1.0 in folder: /home/name/Arduino/hardware/esp8266com/esp8266/libraries/SPI 
exit status 1
Error compiling for board Generic ESP8266 Module.

```

**Comment by sfranzyshen** [comment]
same with release 1.1.11

**Comment by sfranzyshen** [comment]
uint32_t esp_random(void); is not supported outside of esp-idf & esp8266-rtos (not esp8266-nonos)  ... but it could be ...

[esp32_compat.h]
#define esp_random()                (rand()%UINT32_MAX)

**Comment by sfranzyshen** [comment]
BTW this builds fine on the esp32 platform

**Comment by sfranzyshen** [comment]
same result with latest version 1.2.0
`Using library mDash at version 1.2.0 in folder: /home/name/Arduino/libraries/mDash`

**Comment by sfranzyshen** [comment]
same result with latest version 1.2.2
Using library mDash at version 1.2.2 in folder: /home/name/Arduino/libraries/mDash

**Comment by sfranzyshen** [comment]
same result with latest version 1.2.3
Using library mDash at version 1.2.3 in folder: /home/name/Arduino/libraries/mDash

**Comment by sfranzyshen** [comment]
... 1.2.4

**Comment by sfranzyshen** [comment]
... 1.2.5

**Comment by sfranzyshen** [comment]
... 1.2.6

**Comment by sfranzyshen** [comment]
... 1.2.7 ... 1.2.8 ... can we assume that esp8266 support has been dropped?

**Comment by cpq** [comment]
Yeah, esp8266 support is dropped for now,
the plan is to re-enable that in Q1/Q2 2021
