### ISSUE TITLE
Are source files available to build libmdash.a?

### ISSUE THREAD

**Issue by geert56** [cesanta/mDash#7]
I am trying to use the mDash library in Linux. src/linux-x64/libmdash.a seems to be a 32-bit elf library and not 64-bit. Also, this library cannot be loaded by ld. I get the following error:
`/usr/bin/ld: ../src/linux-x64/libmDash.a: unrecognized relocation (0x2b) in section .text`
So it would be great to have access to the source to build libmdash.a from scratch.

**Comment by cpq** [comment]
This library is close-sourced and there are no plans currently to open it.
For the reference, a Linux version was built by a Linux docker container docker.io/mdashnet/cc.
Your might use it to build your linux binary:

```
$ docker run -v $(pwd):$(pwd) -w $(pwd) docker.io/mdashnet/cc cc myfile.c -lmDash -Lmdash/src/linux-x64
```
