### ISSUE TITLE
ESP8266 compatibility with mDash

### ISSUE THREAD

**Issue by rishinikhil** [cesanta/mDash#9]
Hi,

I wished to have clarity on the compatibility of ESP8266 module with mDash. I am unable to find clear cut documentation/instructions about whether ESP8266 is supported by mDash or not.

Kindly share what all works for ESP8266 in mDash, and does arduino IDE work?

**Comment by cpq** [comment]
@rishinikhil , ESP8266 is not supported by this library.
Mongoose OS + ESP8266 works well with mDash , but not this Arduino library.
